services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    environment: 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    ports:
      - 5000:8080 # http
      - 5001:8081 # https
    depends_on:
      - sql-server
    networks:
      - app-net

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd123
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-net

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
     - 18888:18888
    networks:
      - app-net

volumes:
  sql-data:
  
networks:
  app-net: